/*
 * This file has been automatically generated by the jrl-cmakemodules.
 * Please see https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/config.hh.cmake for details.
*/

#ifndef HPP_PRACTICALS_CONFIG_HH
# define HPP_PRACTICALS_CONFIG_HH

// Package version (header).
# define HPP_PRACTICALS_VERSION_UNKNOWN_TAG 0 // Used to mention that the current version is unknown.
# define HPP_PRACTICALS_VERSION "6.1.0"
# define HPP_PRACTICALS_MAJOR_VERSION 6
# define HPP_PRACTICALS_MINOR_VERSION 1
# define HPP_PRACTICALS_PATCH_VERSION 0

#define HPP_PRACTICALS_VERSION_AT_LEAST(major, minor, patch) (HPP_PRACTICALS_MAJOR_VERSION>major || (HPP_PRACTICALS_MAJOR_VERSION>=major && \
                                                             (HPP_PRACTICALS_MINOR_VERSION>minor || (HPP_PRACTICALS_MINOR_VERSION>=minor && \
                                                                                                     HPP_PRACTICALS_PATCH_VERSION>=patch))))

#define HPP_PRACTICALS_VERSION_AT_MOST(major, minor, patch) (HPP_PRACTICALS_MAJOR_VERSION<major || (HPP_PRACTICALS_MAJOR_VERSION<=major && \
                                                            (HPP_PRACTICALS_MINOR_VERSION<minor || (HPP_PRACTICALS_MINOR_VERSION<=minor && \
                                                                                                     HPP_PRACTICALS_PATCH_VERSION<=patch))))

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
//
// Explicit template instantiation on Windows need to add
// dllexport on the definition and dllimport on the declaration.
// The XXX_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI macro
// should be set on the declaration while
// the XXX_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI macro
// should be set on the definition.
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define HPP_PRACTICALS_DLLIMPORT __declspec(dllimport)
#  define HPP_PRACTICALS_DLLEXPORT __declspec(dllexport)
#  define HPP_PRACTICALS_DLLLOCAL
#  define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT __declspec(dllimport)
#  define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#  define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT __declspec(dllimport)
#  define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT __declspec(dllexport)
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define HPP_PRACTICALS_DLLIMPORT __attribute__ ((visibility("default")))
#   define HPP_PRACTICALS_DLLEXPORT __attribute__ ((visibility("default")))
#   define HPP_PRACTICALS_DLLLOCAL  __attribute__ ((visibility("hidden")))
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT __attribute__ ((visibility("default")))
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT __attribute__ ((visibility("default")))
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define HPP_PRACTICALS_DLLIMPORT
#   define HPP_PRACTICALS_DLLEXPORT
#   define HPP_PRACTICALS_DLLLOCAL
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef HPP_PRACTICALS_STATIC
// If one is using the library statically, get rid of
// extra information and use standard explicit template
// instantiation keyword.
#  define HPP_PRACTICALS_DLLAPI
#  define HPP_PRACTICALS_LOCAL
#  define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DECLARATION extern template
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export and
// define the right explicit template instantiation keyword.
#  ifdef hpp_practicals_EXPORTS
#   define HPP_PRACTICALS_DLLAPI HPP_PRACTICALS_DLLEXPORT
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  else
#   define HPP_PRACTICALS_DLLAPI HPP_PRACTICALS_DLLIMPORT
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT
#   define HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI HPP_PRACTICALS_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#  endif // HPP_PRACTICALS_EXPORTS
#  define HPP_PRACTICALS_LOCAL HPP_PRACTICALS_DLLLOCAL
# endif // HPP_PRACTICALS_STATIC
#endif //! HPP_PRACTICALS_CONFIG_HH
